#
# Login Enterprise
# v7.0-preview [API Console (Swagger)](/publicApi/swagger/index.html?urls.primaryName=Login%20Enterprise%20API%20v7-preview), [Documentation (ReDoc)](/publicApi/v7-preview/docs/index.html)  v6.0 [API Console (Swagger)](/publicApi/swagger/index.html?urls.primaryName=Login%20Enterprise%20API%20v6), [Documentation (ReDoc)](/publicApi/v6/docs/index.html)  v5.0 [API Console (Swagger)](/publicApi/swagger/index.html?urls.primaryName=Login%20Enterprise%20API%20v5), [Documentation (ReDoc)](/publicApi/v5/docs/index.html)  v4.0 [API Console (Swagger)](/publicApi/swagger/index.html?urls.primaryName=Login%20Enterprise%20API%20v4), [Documentation (ReDoc)](/publicApi/v4/docs/index.html)    <br><b>API v7 (preview) – Introduced in Login Enterprise v5.0 and subject to breaking changes when API v7 becomes generally available.</b></br> <br><b>API v6 – is the recommended version to use. It is the actively developed version starting with Login Enterprise v4.10.</b></br> <br><b>API v5 – is currently supported but unmaintained as of v4.10.</b></br> <br><b>API v4 – is deprecated starting with v4.10. Will be removed in Q3 2023.</b></br>   The Login Enterprise Public API provides documentation and Swagger per version within the product. For additional information please refer to the [documentation](https://support.loginvsi.com/hc/en-us/articles/360009534760) on our website. 
# Version: 7.0-preview
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

Represents a series of collected appliance health metrics.

.PARAMETER MetricId
Unique identifier for the metric.
.PARAMETER DisplayName
Human-readable name for the metric.
.PARAMETER Unit
Unit of measurement for the metric value.
.PARAMETER DataPoints
Time series data points
.OUTPUTS

ApplianceHealthMetricSeries<PSCustomObject>
#>

function Initialize-LEApplianceHealthMetricSeries {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${MetricId},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${DisplayName},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Unit},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${DataPoints}
    )

    Process {
        'Creating PSCustomObject: PSLoginEnterprise => LEApplianceHealthMetricSeries' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "metricId" = ${MetricId}
            "displayName" = ${DisplayName}
            "unit" = ${Unit}
            "dataPoints" = ${DataPoints}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to ApplianceHealthMetricSeries<PSCustomObject>

.DESCRIPTION

Convert from JSON to ApplianceHealthMetricSeries<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

ApplianceHealthMetricSeries<PSCustomObject>
#>
function ConvertFrom-LEJsonToApplianceHealthMetricSeries {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSLoginEnterprise => LEApplianceHealthMetricSeries' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in LEApplianceHealthMetricSeries
        $AllProperties = ("metricId", "displayName", "unit", "dataPoints")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "metricId"))) { #optional property not found
            $MetricId = $null
        } else {
            $MetricId = $JsonParameters.PSobject.Properties["metricId"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "displayName"))) { #optional property not found
            $DisplayName = $null
        } else {
            $DisplayName = $JsonParameters.PSobject.Properties["displayName"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "unit"))) { #optional property not found
            $Unit = $null
        } else {
            $Unit = $JsonParameters.PSobject.Properties["unit"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "dataPoints"))) { #optional property not found
            $DataPoints = $null
        } else {
            $DataPoints = $JsonParameters.PSobject.Properties["dataPoints"].value
        }

        $PSO = [PSCustomObject]@{
            "metricId" = ${MetricId}
            "displayName" = ${DisplayName}
            "unit" = ${Unit}
            "dataPoints" = ${DataPoints}
        }

        return $PSO
    }

}

