#
# Login Enterprise
# v8.0-preview [API Console (Swagger)](/publicApi/swagger/index.html?urls.primaryName=Login%20Enterprise%20API%20v8-preview), [Documentation (ReDoc)](/publicApi/v8-preview/docs/index.html)  v7.0 [API Console (Swagger)](/publicApi/swagger/index.html?urls.primaryName=Login%20Enterprise%20API%20v7), [Documentation (ReDoc)](/publicApi/v7/docs/index.html)  v6.0 [API Console (Swagger)](/publicApi/swagger/index.html?urls.primaryName=Login%20Enterprise%20API%20v6), [Documentation (ReDoc)](/publicApi/v6/docs/index.html)    <br><b>API v8 (preview) – Introduced in Login Enterprise v6.0 and subject to breaking changes.</b></br> <br><b>API v7 – is the recommended version to use. It is the actively developed version starting with Login Enterprise v6.0.</b></br> <br><b>API v6 – is currently supported, but unmaintained as of v6.0.</b></br> <br><b>API v5 and v4 - These versions are removed in v6.0.</b></br>   The Login Enterprise Public API provides documentation and Swagger per version within the product. For additional information please refer to the [documentation](https://support.loginvsi.com/hc/en-us/articles/360009534760) on our website. 
# Version: 7.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSLoginEnterprise' -name 'ApplicationGroupAccessApi' {
    Context 'Invoke-ConfigurationBulkAddApplicationGroupAccess' {
        It 'Test Invoke-ConfigurationBulkAddApplicationGroupAccess' {
            #$TestResult = Invoke-ConfigurationBulkAddApplicationGroupAccess -ApplicationGroupAccessBulkUpdate "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-ConfigurationBulkRemoveApplicationGroupAccess' {
        It 'Test Invoke-ConfigurationBulkRemoveApplicationGroupAccess' {
            #$TestResult = Invoke-ConfigurationBulkRemoveApplicationGroupAccess -ApplicationGroupAccessBulkUpdate "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-ConfigurationBulkReplaceApplicationGroupAccess' {
        It 'Test Invoke-ConfigurationBulkReplaceApplicationGroupAccess' {
            #$TestResult = Invoke-ConfigurationBulkReplaceApplicationGroupAccess -ApplicationGroupAccessBulkUpdate "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-ConfigurationGetApplicationGroupAccess' {
        It 'Test Invoke-ConfigurationGetApplicationGroupAccess' {
            #$TestResult = Invoke-ConfigurationGetApplicationGroupAccess -ApplicationGroupId "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-ConfigurationGetApplicationGroupsByRole' {
        It 'Test Invoke-ConfigurationGetApplicationGroupsByRole' {
            #$TestResult = Invoke-ConfigurationGetApplicationGroupsByRole -RoleId "TEST_VALUE" -OrderBy "TEST_VALUE" -Direction "TEST_VALUE" -Count "TEST_VALUE" -Offset "TEST_VALUE" -IncludeTotalCount "TEST_VALUE" -Filter "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-ConfigurationUpdateApplicationGroupAccess' {
        It 'Test Invoke-ConfigurationUpdateApplicationGroupAccess' {
            #$TestResult = Invoke-ConfigurationUpdateApplicationGroupAccess -ApplicationGroupId "TEST_VALUE" -RequestBody "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

}
