#
# Login Enterprise
# v8.0-preview [API Console (Swagger)](/publicApi/swagger/index.html?urls.primaryName=Login%20Enterprise%20API%20v8-preview), [Documentation (ReDoc)](/publicApi/v8-preview/docs/index.html)  v7.0 [API Console (Swagger)](/publicApi/swagger/index.html?urls.primaryName=Login%20Enterprise%20API%20v7), [Documentation (ReDoc)](/publicApi/v7/docs/index.html)  v6.0 [API Console (Swagger)](/publicApi/swagger/index.html?urls.primaryName=Login%20Enterprise%20API%20v6), [Documentation (ReDoc)](/publicApi/v6/docs/index.html)    <br><b>API v8 (preview) – Introduced in Login Enterprise v6.0 and subject to breaking changes.</b></br> <br><b>API v7 – is the recommended version to use. It is the actively developed version starting with Login Enterprise v6.0.</b></br> <br><b>API v6 – is currently supported, but unmaintained as of v6.0.</b></br> <br><b>API v5 and v4 - These versions are removed in v6.0.</b></br>   The Login Enterprise Public API provides documentation and Swagger per version within the product. For additional information please refer to the [documentation](https://support.loginvsi.com/hc/en-us/articles/360009534760) on our website. 
# Version: 7.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSLoginEnterprise' -name 'LELENotificationApi' {
    Context 'New-LEContinuousTestNotification' {
        It 'Test New-LEContinuousTestNotification' {
            #$TestResult = New-LEContinuousTestNotification -TestId "TEST_VALUE" -ThresholdNotificationCreate "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-LEDeleteContinuousTestNotification' {
        It 'Test Invoke-LEDeleteContinuousTestNotification' {
            #$TestResult = Invoke-LEDeleteContinuousTestNotification -TestId "TEST_VALUE" -NotificationId "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-LEContinuousTestNotifications' {
        It 'Test Get-LEContinuousTestNotifications' {
            #$TestResult = Get-LEContinuousTestNotifications -TestId "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Update-LEContinuousTestNotification' {
        It 'Test Update-LEContinuousTestNotification' {
            #$TestResult = Update-LEContinuousTestNotification -TestId "TEST_VALUE" -NotificationId "TEST_VALUE" -ConfigurationUpdateContinuousTestNotificationRequest "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

}
