#
# Login Enterprise
# v8.0-preview [API Console (Swagger)](/publicApi/swagger/index.html?urls.primaryName=Login%20Enterprise%20API%20v8-preview), [Documentation (ReDoc)](/publicApi/v8-preview/docs/index.html)  v7.0 [API Console (Swagger)](/publicApi/swagger/index.html?urls.primaryName=Login%20Enterprise%20API%20v7), [Documentation (ReDoc)](/publicApi/v7/docs/index.html)  v6.0 [API Console (Swagger)](/publicApi/swagger/index.html?urls.primaryName=Login%20Enterprise%20API%20v6), [Documentation (ReDoc)](/publicApi/v6/docs/index.html)    <br><b>API v8 (preview) – Introduced in Login Enterprise v6.0 and subject to breaking changes.</b></br> <br><b>API v7 – is the recommended version to use. It is the actively developed version starting with Login Enterprise v6.0.</b></br> <br><b>API v6 – is currently supported, but unmaintained as of v6.0.</b></br> <br><b>API v5 and v4 - These versions are removed in v6.0.</b></br>   The Login Enterprise Public API provides documentation and Swagger per version within the product. For additional information please refer to the [documentation](https://support.loginvsi.com/hc/en-us/articles/360009534760) on our website. 
# Version: 7.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

Load Test Statistics

.PARAMETER EuxScores
Eux Score (1 minute offset)
.PARAMETER BaseTimestamp
Starting timestamp
.PARAMETER VsiMaxOffset
VSImax reached offset
.OUTPUTS

LoadTestRunStatistics<PSCustomObject>
#>

function Initialize-LELoadTestRunStatistics {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [Double[]]
        ${EuxScores},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[System.DateTime]]
        ${BaseTimestamp},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${VsiMaxOffset}
    )

    Process {
        'Creating PSCustomObject: PSLoginEnterprise => LELoadTestRunStatistics' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "euxScores" = ${EuxScores}
            "baseTimestamp" = ${BaseTimestamp}
            "vsiMaxOffset" = ${VsiMaxOffset}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to LoadTestRunStatistics<PSCustomObject>

.DESCRIPTION

Convert from JSON to LoadTestRunStatistics<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

LoadTestRunStatistics<PSCustomObject>
#>
function ConvertFrom-LEJsonToLoadTestRunStatistics {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSLoginEnterprise => LELoadTestRunStatistics' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in LELoadTestRunStatistics
        $AllProperties = ("euxScores", "baseTimestamp", "vsiMaxOffset")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "euxScores"))) { #optional property not found
            $EuxScores = $null
        } else {
            $EuxScores = $JsonParameters.PSobject.Properties["euxScores"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "baseTimestamp"))) { #optional property not found
            $BaseTimestamp = $null
        } else {
            $BaseTimestamp = $JsonParameters.PSobject.Properties["baseTimestamp"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "vsiMaxOffset"))) { #optional property not found
            $VsiMaxOffset = $null
        } else {
            $VsiMaxOffset = $JsonParameters.PSobject.Properties["vsiMaxOffset"].value
        }

        $PSO = [PSCustomObject]@{
            "euxScores" = ${EuxScores}
            "baseTimestamp" = ${BaseTimestamp}
            "vsiMaxOffset" = ${VsiMaxOffset}
        }

        return $PSO
    }

}

